### ISSUE TITLE
Can't load Plugin

### ISSUE THREAD

**Issue by zanaviska** [ADAPT/ADAPT-Visualizer#17]
I downloaded ExamplePlugin project from https://github.com/ADAPT/ADAPT-Samples, and successfully build it after ``` dotnet restore ``` command in Nuget packet manager console. After that, I followed [this](https://youtu.be/trkYM_uTuRM?t=2565) tutorial, and my plugin was not loaded
![image](https://user-images.githubusercontent.com/31745527/89098890-07872600-d3f4-11ea-8468-4263c20bec4f.png)

I also tried different plugin location, but nothing helps

**Comment by knelson-farmbeltnorth** [comment]
I suspect the issue was incompatibility between ADAPT 1.2 and 2.0.   The Samples have not been updated for some time.

We are actually in the process of migrating the samples to a new repository.  Please see the development branch of https://github.com/ADAPT/Examples and please advise if the upgraded ExamplePlugin at that location does not solve your issue.
